# Default state for all rules.
default: true

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content.
MD024:
  # Only check sibling headings.
  siblings_only: true

# MD013/line-length: Line length.
MD013: false

# MD041/first-line-heading/first-line-h1: First line in a file should be a top-level heading.
MD041: false

# MD040/fenced-code-language Fenced code blocks should have a language specified
MD040: false
